module.exports = {
  "docs": [
    {"_id":"_design/envs","language":"javascript","views":{"project":{"map":"function(doc) {\n\tif (doc.type == 'env') {\n\t\temit(doc.org + '/' + doc.project, doc);\n\t}\n}"},"org":{"map":"function(doc) {\n\tif (doc.type == 'env') {\n\t\temit(doc.org, doc);\n\t}\n}"},"name":{"map":"function(doc) {\n\tif (doc.type == 'env') {\n\t\temit(doc.org + '/' + doc.project + '/' + doc.name.toLowerCase(), doc);\n\t}\n}"}}},
    {"_id":"_design/orgs","language":"javascript","views":{"name":{"map":"function(doc) {\n\tif (doc.type == 'org') {\n\t\temit(doc.name.toLowerCase(), doc);\n\t}\n}"},"user":{"map":"function(doc) {\n\tif (doc.type == 'org') {\n\t\tObject.keys(doc.users).forEach(function (user) {\n\t\t\temit(user, doc);\n\t\t});\n\t}\n}"}}},
    {"_id":"_design/projects","language":"javascript","views":{"name":{"map":"function(doc) {\n\tif (doc.type == 'project') {\n\t\temit(doc.org + '/' + doc.name.toLowerCase(), doc);\n\t}\n}"},"user":{"map":"function(doc) {\n\tif (doc.type == 'project') {\n\t\tObject.keys(doc.users).forEach(function (user) {\n\t\t\temit(doc.org + '/' + user, doc);\n\t\t});\n\t}\n}"},"org":{"map":"function (doc) {\n\tif (doc.type == 'project') {\n\t\temit(doc.org, doc);\n\t}\n}"},"team":{"map":"function(doc) {\n\tif (doc.type == 'project') {\n\t\tObject.keys(doc.teams).forEach(function (team) {\n\t\t\temit(doc.org + '/' + team, doc);\n\t\t});\n\t}\n}"}}},
    {"_id":"_design/teams","language":"javascript","views":{"name":{"map":"function(doc) {\n\tif (doc.type == 'team') {\n\t\temit(doc.org + '/' + doc.name.toLowerCase(), doc);\n\t}\n}"},"org":{"map":"function (doc) {\n\tif (doc.type == 'team') {\n\t\temit(doc.org, doc);\n\t}\n}"},"user":{"map":"function(doc) {\n\tif (doc.type == 'team') {\n\t\tObject.keys(doc.users).forEach(function (user) {\n\t\t\temit(doc.org + '/' + user, doc);\n\t\t});\n\t}\n}"}}},
    {"_id":"_design/users","language":"javascript","views":{"email":{"map":"function(doc) {\n\tif (doc.type == 'user') {\n\t\temit(doc.email, doc);\n\t}\n}"},"token":{"map":"function(doc) {\n\tif (doc.type == 'user' && doc.access_token) {\n\t\temit(doc.email, doc);\n\t}\n}"}}},
    {"_id":"orgs/confyio","name":"Confyio","email":"admin@confy.io","type":"org","owner":"pksunkara","plan":"none","users":{"pksunkara":3,"whatupdave":1,"vanstee":1}},
    {"_id":"orgs/confyio/projects/knowledgebase","name":"KnowledgeBase","description":"Wiki & FAQ support","type":"project","teams":{"owners":true,"consultants":true},"org":"confyio","users":{"pksunkara":2,"whatupdave":1,"vanstee":1}},
    {"_id":"orgs/confyio/projects/main","name":"Main","description":"Main app","type":"project","teams":{"owners":true,"engineering":true},"org":"confyio","users":{"pksunkara":2}},
    {"_id":"orgs/confyio/projects/urlshortener","name":"UrlShortener","description":"Service to be used by bots","type":"project","teams":{"owners":true},"org":"confyio","users":{"pksunkara":1}},
    {"_id":"orgs/confyio/projects/knowledgebase/envs/production","name":"Production","description":"Production environment","org":"confyio","project":"knowledgebase","type":"env","config":{"port":8000,"database":{"port":5984,"url":"http://db.confy.io","name":"support"}}},
    {"_id":"orgs/confyio/projects/main/envs/production","name":"Production","description":"Production environment","org":"confyio","project":"main","type":"env","config":{"port":5000,"name":"confy","database":{"port":5984,"url":"http://db.confy.io","user":"admin","pass":"secret"}}},
    {"_id":"orgs/confyio/projects/main/envs/staging","name":"Staging","description":"Staging environment","org":"confyio","project":"main","type":"env","config":{"port":5000,"name":"confy","database":{"port":5984,"url":"http://localhost"}}},
    {"_id":"orgs/confyio/projects/main/envs/qa","name":"QA","description":"Quality assurance guys","org":"confyio","project":"main","type":"env","config":{"port":5000,"name":"confy","database":{"port":5984,"url":"http://staging.confy.io","user":"admin","pass":"secret"}}},
    {"_id":"orgs/confyio/projects/urlshortener/envs/production","name":"Production","description":"Production environment","org":"confyio","project":"urlshortener","type":"env","config":{"port":3333,"database":{"port":5984,"url":"http://db.confy.io","name":"url"}}},
    {"_id":"orgs/confyio/teams/owners","name":"Owners","description":"Has access to all projects","type":"team","users":{"pksunkara":true},"org":"confyio"},
    {"_id":"orgs/confyio/teams/consultants","name":"Consultants","description":"Consultants will have restricted access to the projects","users":{"pksunkara":true,"whatupdave":true,"vanstee":true},"org":"confyio","type":"team"},
    {"_id":"orgs/confyio/teams/engineering","name":"Engineering","description":"Engineers in the company","users":{"pksunkara":true},"org":"confyio","type":"team"},
    {"_id":"orgs/app123/projects/app","name":"App","description":"Heroku application","type":"project","teams":{"owners":true},"org":"app123","users":{"app123":1}},
    {"_id":"orgs/app123/projects/app/envs/production","name":"Production","description":"Production environment","org":"app123","project":"app","type":"env","config":{"port":8000}},
    {"_id":"orgs/app123","name":"app123","email":"app123@heroku.com","type":"org","owner":"app123","plan":"heroku","users":{"app123":1}},
    {"_id":"orgs/app123/teams/owners","name":"Owners","description":"Has access to all projects","users":{"app123":true},"org":"app123","type":"team"},
    {"_id":"orgs/pksunkara","name":"pksunkara","email":"pavan.sss1991@gmail.com","type":"org","owner":"pksunkara","plan":"none","users":{"pksunkara":1}},
    {"_id":"orgs/pksunkara/teams/owners","name":"Owners","description":"Has access to all projects","users":{"pksunkara":true},"org":"pksunkara","type":"team"},
    {"_id":"orgs/sunkara","name":"Sunkara","email":"pavan.sss1991@gmail.com","type":"org","owner":"pksunkara","plan":"none","users":{"pksunkara":1}},
    {"_id":"orgs/sunkara/teams/owners","name":"Owners","description":"Has access to all projects","users":{"pksunkara":true},"org":"sunkara","type":"team"},
    {"_id":"orgs/vanstee","name":"vanstee","email":"patrick@vanstee.me","type":"org","owner":"vanstee","plan":"none","users":{"vanstee":1}},
    {"_id":"orgs/vanstee/teams/owners","name":"Owners","description":"Has access to all projects","users":{"vanstee":true},"org":"vanstee","type":"team"},
    {"_id":"orgs/whatupdave","name":"whatupdave","email":"dave@snappyco.de","type":"org","owner":"whatupdave","plan":"none","users":{"whatupdave":1}},
    {"_id":"orgs/whatupdave/teams/owners","name":"Owners","description":"Has access to all projects","users":{"whatupdave":true},"org":"whatupdave","type":"team"},
    {"_id":"orgs/zdenek","name":"zdenek","email":"z@apiary.io","owner":"zdenek","plan":"none","type":"org","users":{"zdenek":1}},
    {"_id":"orgs/zdenek/teams/owners","name":"Owners","description":"Has access to all projects","users":{"zdenek":true},"org":"zdenek","type":"team"},
    {"_id":"users/app123","username":"app123","email":"app123@heroku.com","password":"$2a$10$h.tbQoE/vDHq1eZuT0o0guXz1k/vh9ffQIHaJ0PTWUpnSziOFvcba","type":"user","verified":true,"heroku":true},
    {"_id":"users/pksunkara","username":"pksunkara","email":"pavan.sss1991@gmail.com","password":"$2a$10$h.tbQoE/vDHq1eZuT0o0guXz1k/vh9ffQIHaJ0PTWUpnSziOFvcba","type":"user","verified":true},
    {"_id":"users/vanstee","username":"vanstee","email":"patrick@vanstee.me","password":"$2a$10$5eJFpD749KIaUXHhK/LVHOH3uQW1fdyJkZV7VLKpEEccDKDzB.dq6","type":"user","verified":true},
    {"_id":"users/whatupdave","username":"whatupdave","email":"dave@snappyco.de","password":"$2a$10$zLU2YvIuUH8EiGgqOc0g.exDZXobiXlfLy20yifWnuD/7xqvaxl3y","type":"user","verified":true},
    {"_id":"users/zdenek","username":"zdenek","email":"z@apiary.io","password":"$2a$10$MLXwXjnxk1covLgEaAR8YeOQYQcO7INoHpfkIDi3.7pmwtsJbGw6.","type":"user","verified":true},
  ]
};
